networks:
  advanced-web-network:
    driver: bridge
    name: advanced-web-network

volumes:
  db-data:

services:
  advanced-web-backend-service:
    image: ppolariss/advanced_web_backend:latest
    restart: unless-stopped
    environment:
      - DB_URL=user:password@tcp(db-service:3306)/advanced_web?charset=utf8mb4&parseTime=True&loc=Local
      - MOSS_URL=${MOSS_URL}
      - MOSS_API_KEY=${MOSS_API_KEY}
    networks:
      - advanced-web-network
    ports:
      - "8080:8080"
    container_name: advanced-web-backend-service
    volumes:
      - /home/solaris/Desktop/AdvancedWeb-Backend/html:/app/html

  db-service:
    container_name: db-service
    image: mysql:8.0.34
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: advanced_web
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - advanced-web-network
    ports:
      - "13306:3306"
    volumes:
      - db-data:/var/lib/mysql

  driving-service:
    container_name: driving-service
    image: ppolariss/driving:latest
    restart: unless-stopped
    ports:
      - "3000:3000"

  advanced-web-frontend-service:
    container_name: frontend-service
    image: ppolariss/advanced_web_frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /home/solaris/Desktop/AdvancedWeb-Backend/assets:/usr/share/nginx/html/assets