version: '1'

networks:
  advanced-web-network:
    driver: bridge
    name: advanced-web-network

services:
  advanced-web-backend-service:
    image: ppolariss/advanced_web_backend:v1
    environment:
      - DB_URL=root:root@tcp(host.docker.internal:3306)/advanced_web?charset=utf8mb4&parseTime=True&loc=Local
    networks:
      - advanced-web-network
    ports:
      - "8080:8080"
    container_name: advanced-web-backend-service