networks:
  advanced-web-network:
    driver: bridge
    name: advanced-web-network

volumes:
  db-data:

services:
  advanced-web-backend-service:
    image: ppolariss/advanced_web_backend:latest
    restart: unless-stopped
    environment:
      - DB_URL=user:password@tcp(db-service:3306)/advanced_web?charset=utf8mb4&parseTime=True&loc=Local
      - MOSS_URL=${MOSS_URL}
      - DB_URL=${DB_URL}
    networks:
      - advanced-web-network
    ports:
      - "8080:8080"
    container_name: advanced-web-backend-service

  db-service:
    container_name: db-service
    image: mysql:8.0.34
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: advanced_web
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - advanced-web-network
    ports:
      - "13306:3306"
    volumes:
      - db-data:/var/lib/mysql
